### ISSUE TITLE
Sarif 3.0 give AttributeError: 'SarifFileSet' object has no attribute 'get_issue_code_histogram' when compating directories.

### ISSUE THREAD

**Issue by chaudron** [microsoft/sarif-tools#58]
With Sarif 3.0 I get the following error when comparing directories: AttributeError: 'SarifFileSet' object has no attribute 'get_issue_code_histogram'

```
[ebuild:~/...g-analyzer-results_I]$ sarif --check note diff 2024-09-11-163044-71291-1/ 2024-09-11-163456-86579-1/
Traceback (most recent call last):
  File "/home/echaudron/.local/bin/sarif", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/echaudron/.local/lib/python3.12/site-packages/sarif/cmdline/main.py", line 61, in main
    exitcode = args.func(args)
               ^^^^^^^^^^^^^^^
  File "/home/echaudron/.local/lib/python3.12/site-packages/sarif/cmdline/main.py", line 354, in _diff_command
    return diff_op.print_diff(original_sarif, new_sarif, args.output, args.check)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/echaudron/.local/lib/python3.12/site-packages/sarif/operations/diff_op.py", line 39, in print_diff
    diff = calc_diff(original_sarif, new_sarif)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/echaudron/.local/lib/python3.12/site-packages/sarif/operations/diff_op.py", line 141, in calc_diff
    original_histogram = dict(original_sarif.get_issue_code_histogram(severity))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SarifFileSet' object has no attribute 'get_issue_code_histogram'
```

**Comment by balgillo** [comment]
Thanks for raising this, and sorry for the regression.  v3.0.1 is now on PyPI with a fix.

**Comment by chaudron** [comment]
Thanks for the quick turnaround, will undo our OVS upstream CI.
